steps:
  # Install dependencies
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", ".", "--user"]

  # Generate ambient GCP credentials
  - name: python
    entrypoint: python
    args: ["-m", "id", "throwaway"]
    env:
      - "GOOGLE_SERVICE_ACCOUNT_NAME=sigstore-python-test@projectsigstore.iam.gserviceaccount.com"
