name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # NOTE: We intentionally lint against our minimum supported Python.
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: deps
        run: make dev ID_EXTRA=lint

      - name: lint
        run: make lint

  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # NOTE: We intentionally check `--help` rendering against our minimum Python,
      # since it changes slightly between Python versions.
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: deps
        run: make dev

      - name: check-readme
        run: make check-readme

  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # adapted from Warehouse's bin/licenses
      - run: |
          for fn in $(find . -type f -name "*.py"); do
            if [[ ! "$(head -5 $fn | grep "^ *\(#\|\*\|\/\/\) .* License\(d*\)")" ]]; then
              echo "${fn} is missing a license"
              exit 1
            fi
          done

  all-lints-pass:
    if: always()

    needs:
      - lint
      - check-readme
      - licenses

    runs-on: ubuntu-latest

    steps:
      - name: check lint jobs
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
